### ISSUE TITLE
using with convoy-NFS

### ISSUE THREAD

**Issue by kkvilekval** [sshipway/Portus#2]
I am trying to get working using convoy-nfs as the storage backend for the shared storage. Any suggestions?

**Comment by sshipway** [comment]
This should be possible, but you may need to create multiple volumes in convoy.

Note that the Portus container has 2 important mounts --
- The certificates (where certs are created/used)
- The NGINX config dir (where an nginx config is written for use)

If you are not using NGINX you don't need the second, but the first will definitely be necessary and should be shared with the registry container (which also will have a separate mount for the actual data).

So when you start up the portus container, you'll have something like:

```
volume_driver: convoy-nfs
volumes:
- registry_certs:/certs
- registry_proxy: /etc/nginx/conf.d
```

Then you'll do something similar with your registry container, to mount registry_certs and (probably) registry_data to /certs and /var/lib/registry respectively.

Since you're using Convoy, you're likely using Rancher, so you could rewrite the Registry template to take a list of volume names (or a voume name prefix) rather than a directory name vor the volumes.

**Comment by sshipway** [comment]
There's an example of a stack template for Portus using Convoy in https://github.com/sshipway/community-catalog

**Comment by kkvilekval** [comment]
wow fantastic.. I was now able to deploy on convory-nfs.   I am wondering about using the built in rancher load-balancer which can pickup certificates created by letsencrypt automatically.  In that case the load balancer is haproxy (with ssl termination) sending to nginx so  you might not need to (re)create the cerificates.

**Comment by sshipway** [comment]
Closing as the original request was solved
